project_name: iris

release:
  disable: true
  draft: true
  prerelease: auto

builds:
  - &xbuildd
    id: irisd-darwin-amd64
    main: ./cmd/irisd
    binary: irisd
    goos:
      - darwin
    goarch:
      - amd64
    tags:
      - netgo
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags: &ldflags
      - -s -w
      - -X github.com/zenanetwork/iris/version.Name=iris
      - -X github.com/zenanetwork/iris/version.ServerName=irisd
      - -X github.com/zenanetwork/iris/version.ClientName=iriscli
      - -X github.com/zenanetwork/iris/version.Version={{.Version}}
      - -X github.com/zenanetwork/iris/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.Name=iris
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=irisd
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=iriscli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  - <<: *xbuildd
    id: irisd-darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++

  - <<: *xbuildd
    id: irisd-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      - -s -w -extldflags "-static"
      - -X github.com/zenanetwork/iris/version.Name=iris
      - -X github.com/zenanetwork/iris/version.ServerName=irisd
      - -X github.com/zenanetwork/iris/version.ClientName=iriscli
      - -X github.com/zenanetwork/iris/version.Version={{.Version}}
      - -X github.com/zenanetwork/iris/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.Name=iris
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=irisd
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=iriscli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  - <<: *xbuildd
    id: irisd-linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      - -s -w -extldflags "-static"
      - -X github.com/zenanetwork/iris/version.Name=iris
      - -X github.com/zenanetwork/iris/version.ServerName=irisd
      - -X github.com/zenanetwork/iris/version.ClientName=iriscli
      - -X github.com/zenanetwork/iris/version.Version={{.Version}}
      - -X github.com/zenanetwork/iris/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.Name=iris
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=irisd
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=iriscli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  # iriscli

  - &xbuildcli
    id: iriscli-darwin-amd64
    main: ./cmd/iriscli
    binary: iriscli
    goos:
      - darwin
    goarch:
      - amd64
    tags:
      - netgo
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      - -s -w
      - -X github.com/zenanetwork/iris/version.Name=iris
      - -X github.com/zenanetwork/iris/version.ServerName=irisd
      - -X github.com/zenanetwork/iris/version.ClientName=iriscli
      - -X github.com/zenanetwork/iris/version.Version={{.Version}}
      - -X github.com/zenanetwork/iris/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.Name=iris
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=irisd
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=iriscli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  - <<: *xbuildcli
    id: iriscli-darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++

  - <<: *xbuildcli
    id: iriscli-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      - -linkmode external -extldflags "-static"
      - -X github.com/zenanetwork/iris/version.Name=iris
      - -X github.com/zenanetwork/iris/version.ServerName=irisd
      - -X github.com/zenanetwork/iris/version.ClientName=iriscli
      - -X github.com/zenanetwork/iris/version.Version={{.Version}}
      - -X github.com/zenanetwork/iris/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.Name=iris
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=irisd
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=iriscli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  - <<: *xbuildcli
    id: iriscli-linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      - -linkmode external -extldflags "-static"
      - -X github.com/zenanetwork/iris/version.Name=iris
      - -X github.com/zenanetwork/iris/version.ServerName=irisd
      - -X github.com/zenanetwork/iris/version.ClientName=iriscli
      - -X github.com/zenanetwork/iris/version.Version={{.Version}}
      - -X github.com/zenanetwork/iris/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.Name=iris
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=irisd
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=iriscli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

nfpms:
  - vendor: 0xPolygon
    homepage: https://polygon.technology
    maintainer: Polygon Team <team@polygon.technology>
    description: Polygon Blockchain
    license: GPLv3 LGPLv3

    bindir: /usr/local/bin

    formats:
      - apk
      - deb
      - rpm

    contents:
      - src: builder/files/irisd.service
        dst: /lib/systemd/system/irisd.service
        type: config
      - src: builder/files/genesis-mainnet-v1.json
        dst: /etc/iris/genesis-mainnet-v1.json
        type: config
      - src: builder/files/genesis-testnet-v4.json
        dst: /etc/iris/genesis-testnet-v4.json
        type: config
      - dst: /var/lib/iris
        type: dir
        file_info:
          mode: 0777

    scripts:
      postinstall: builder/files/iris-post-install.sh

snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: amd64
    ids:
      - irisd-linux-amd64
      - iriscli-linux-amd64
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - docker/entrypoint.sh
      - builder/files/genesis-mainnet-v1.json
      - builder/files/genesis-testnet-v4.json

  - image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: arm64
    ids:
      - irisd-linux-arm64
      - iriscli-linux-arm64
    build_flag_templates:
      - --platform=linux/arm64/v8
    extra_files:
      - docker/entrypoint.sh
      - builder/files/genesis-mainnet-v1.json
      - builder/files/genesis-testnet-v4.json

docker_manifests:
  - name_template: 0xpolygon/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-amd64
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: 0xpolygon/{{ .ProjectName }}:latest
    image_templates:
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-amd64
      - 0xpolygon/{{ .ProjectName }}:{{ .Version }}-arm64

announce:
  slack:
    enabled: true
    # The name of the channel that the user selected as a destination for webhook messages.
    channel: "#code-releases"
