name: mainnet_deb_profiles

on:
  push:
    branches:
      - "master"
    paths:
      - "**"
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Variables
      - name: Adding TAG to ENV
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: adding version
        run: |
          NUMERIC_VERSION=$( echo ${{ env.GIT_TAG }} | sed 's/[^0-9.]//g' )
          echo "VERSION=$NUMERIC_VERSION" >> $GITHUB_ENV

      - name: Making directory structure for yaml
        run: mkdir -p packaging/deb/irisd/var/lib/iris/config
      - name: making directory structure for the systemd
        run: mkdir -p packaging/deb/irisd/lib/systemd/system
      - name: delete old control file
        run: rm -rf packaging/deb/irisd/DEBIAN/control

      # Control file creation
      - name: create control file
        run: |
          touch packaging/deb/irisd/DEBIAN/control
          echo "Package: iris-profile" >> packaging/deb/irisd/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/irisd/DEBIAN/control
          echo "Section: base" >> packaging/deb/irisd/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/irisd/DEBIAN/control
          echo "Architecture: all" >> packaging/deb/irisd/DEBIAN/control
          echo "Maintainer: devops@zena.technology" >> packaging/deb/irisd/DEBIAN/control
          echo "Description: iris profile package" >> packaging/deb/irisd/DEBIAN/control

      #### Sentry Profiles ####
      - name: Setting up ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/deb/irisd packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying the postinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: |
          cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
          cp -rp packaging/templates/package_scripts/postrm.profile packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying preinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: |
          cp -rp packaging/templates/package_scripts/preinst packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
          sed -i "s/{{NETWORK}}/${{ env.NETWORK }}/g" packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying iris-config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/iris-config.toml packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/iris/config/iris-config.toml
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/config.toml packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/iris/config/config.toml
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying the prerm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: |
          cp -rp packaging/templates/systemd/irisd-sentry.service packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/irisd.service
          sed -i "s/{{NETWORK}}/${{ env.NETWORK }}/g" packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/irisd.service
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Building ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }} profile
        run: dpkg-deb --build --root-owner-group packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet

      ### Validator Profiles ###
      - name: Prepping iris ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/deb/irisd packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying Postinstall/Postrm script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: |
          cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
          cp -rp packaging/templates/package_scripts/postrm.profile packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying the prerm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying preinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: |
          cp -rp packaging/templates/package_scripts/preinst packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
          sed -i "s/{{NETWORK}}/${{ env.NETWORK }}/g" packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying iris-config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/iris-config.toml packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/iris/config/iris-config.toml
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/config.toml packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/iris/config/config.toml
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: |
          cp -rp packaging/templates/systemd/irisd-validator.service packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/irisd.service
          sed -i "s/{{NETWORK}}/${{env.NETWORK}}/g" packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/irisd.service
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Building iris ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }} profile
        run: dpkg-deb --build --root-owner-group packaging/deb/iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet

      # Shasum
      - name: shasum the iris debian profile package
        run: cd packaging/deb/ && sha256sum iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet

      - name: shasum the iris debian profile package
        run: cd packaging/deb/ && sha256sum iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > iris-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet

      ############ Check and Upload ##########################
      - name: Confirming package built
        run: ls -ltr packaging/deb/ | grep iris

      - name: Release iris Packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_TAG }}
          prerelease: true
          files: |
            packaging/deb/iris-mainnet-**.deb
            packaging/deb/iris-mainnet-**.deb.checksum
