name: packager_deb

on:
  push:
    branches:
      - "master"
    paths:
      - "**"
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      # Variables
      - name: Adding TAG to ENV
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: adding version
        run: |
          NUMERIC_VERSION=$( echo ${{ env.GIT_TAG }} | sed 's/[^0-9.]//g' ) 
          echo "VERSION=$NUMERIC_VERSION" >> $GITHUB_ENV

      - name: Cleaning repo
        run: make clean
      - name: Building for amd64
        run: make build

      - name: Making directory structure
        run: mkdir -p packaging/deb/irisd/usr/bin
      - name: Copying necessary irisd files
        run: cp -rp build/irisd packaging/deb/irisd/usr/bin/
      - name: copying necessary iriscli
        run: cp -rp build/iriscli packaging/deb/irisd/usr/bin/

      # Control file creation
      - name: create control file
        run: |
          touch packaging/deb/irisd/DEBIAN/control
          echo "Package: iris" >> packaging/deb/irisd/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/irisd/DEBIAN/control
          echo "Section: base" >> packaging/deb/irisd/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/irisd/DEBIAN/control
          echo "Architecture: amd64" >> packaging/deb/irisd/DEBIAN/control
          echo "Maintainer: devops@polygon.technology" >> packaging/deb/irisd/DEBIAN/control
          echo "Description: iris binary package" >> packaging/deb/irisd/DEBIAN/control

      - name: Creating package for binary for iris ${{ env.ARCH }}
        run: cp -rp packaging/deb/irisd packaging/deb/iris-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: amd64

      - name: Running package build
        run: dpkg-deb --build --root-owner-group packaging/deb/iris-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: amd64

      - name: Cleaning build directory for arm64 build
        run: make clean

      - name: Updating the apt-get
        run: sudo apt-get update -y

      - name: Adding requirements for cross compile
        run: sudo apt-get install g++-aarch64-linux-gnu gcc-aarch64-linux-gnu

      - name: delete amd64 control file
        run: rm -rf packaging/deb/irisd/DEBIAN/control

      - name: Building iris for arm64
        run: make build-arm

      # Control file creation
      - name: create control file
        run: |
          touch packaging/deb/irisd/DEBIAN/control
          echo "Package: iris" >> packaging/deb/irisd/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/irisd/DEBIAN/control
          echo "Section: base" >> packaging/deb/irisd/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/irisd/DEBIAN/control
          echo "Architecture: arm64" >> packaging/deb/irisd/DEBIAN/control
          echo "Maintainer: devops@polygon.technology" >> packaging/deb/irisd/DEBIAN/control
          echo "Description: iris binary package" >> packaging/deb/irisd/DEBIAN/control

      - name: Copying necessary irisdfiles
        run: cp -rp build/irisd packaging/deb/irisd/usr/bin/
      - name: copying necessary iriscli
        run: cp -rp build/iriscli packaging/deb/irisd/usr/bin/

      - name: Creating package for binary for iris ${{ env.ARCH }}
        run: cp -rp packaging/deb/irisd packaging/deb/iris-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: arm64

      - name: Running package build
        run: dpkg-deb --build --root-owner-group packaging/deb/iris-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: arm64

      # Shasum
      - name: shasum the iris debian package
        run: cd packaging/deb/ && sha256sum iris-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > iris-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: amd64

      - name: shasum the iris debian package
        run: cd packaging/deb/ && sha256sum iris-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > iris-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: arm64

      - name: Release iris Packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_TAG }}
          prerelease: true
          files: |
            packaging/deb/iris**.deb
            packaging/deb/iris**.deb.checksum
